name: Go CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build application
        run: go build -o ecommerce ./cmd

      - name: Build Docker image
        run: docker build -t ecommerce-api .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag ecommerce-api ghcr.io/${{ github.repository_owner }}/ecommerce-api:latest